# Generated by Django 6.0.3 on 2026-05-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_link_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payos_order_code',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
