# Generated by Django 6.0.3 on 2026-05-05 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='food_chef',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='restaurant.category'),
        ),
        migrations.AlterField(
            model_name='food',
            name='dish',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurant.table'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='restaurant.order'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Thời gian kết thúc'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='serve_time',
            field=models.DateTimeField(db_index=True, verbose_name='Thời gian bắt đầu'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='restaurant.table'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='restaurant.food'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
