# Generated by Django 6.0.3 on 2026-05-28 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_order_reservation_alter_order_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_direct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_orders', to='restaurant.table'),
        ),
    ]
