import { StyleSheet } from "react-native";

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: "#f2f4f6",
    },
    container: {
        padding: 20,
        alignItems: "center",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 20,
        gap: 8,
    },
    headerTitle: {
        fontSize: 22,
        fontWeight: "700",
        color: "#1a1a2e",
    },
    card: {
        backgroundColor: "white",
        borderRadius: 20,
        padding: 24,
        width: "100%",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
        marginBottom: 20,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: "700",
        color: "#1a1a2e",
        marginBottom: 6,
    },
    cardSubtitle: {
        fontSize: 13,
        color: "#666",
        textAlign: "center",
        marginBottom: 24,
    },
    qrWrapper: {
        padding: 16,
        backgroundColor: "white",
        borderRadius: 16,
        borderWidth: 2,
        borderColor: "#e3f2fd",
        marginBottom: 24,
        shadowColor: "#1976D2",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    infoBox: {
        width: "100%",
        backgroundColor: "#f8f9fa",
        borderRadius: 12,
        padding: 16,
    },
    infoRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 6,
    },
    infoLabel: {
        fontSize: 14,
        color: "#888",
    },
    infoValue: {
        fontSize: 14,
        fontWeight: "600",
        color: "#1a1a2e",
    },
    infoTotal: {
        fontSize: 16,
        fontWeight: "800",
        color: "#1976D2",
    },
    divider: {
        height: 1,
        backgroundColor: "#e0e0e0",
    },
    checkButton: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#1976D2",
        paddingVertical: 14,
        paddingHorizontal: 40,
        borderRadius: 14,
        width: "100%",
        justifyContent: "center",
        gap: 8,
        marginBottom: 12,
        shadowColor: "#1976D2",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    checkButtonText: {
        color: "white",
        fontSize: 16,
        fontWeight: "700",
    },
    backButton: {
        paddingVertical: 14,
        paddingHorizontal: 40,
        borderRadius: 14,
        width: "100%",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1.5,
        borderColor: "#1976D2",
    },
    backButtonText: {
        color: "#1976D2",
        fontSize: 16,
        fontWeight: "600",
    },
});