import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFF5E5',
        paddingHorizontal: 20,
        paddingTop: 40,
    },
    headerTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#FF6347',
        textAlign: 'center',
        marginBottom: 25,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    formContainer: {
        backgroundColor: '#FFFFFF',
        padding: 25,
        borderRadius: 25,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
    },
    label: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333333',
        marginBottom: 8,
        marginTop: 10,
    },
    input: {
        backgroundColor: '#F5F5F5',
        minHeight: 50,
        borderRadius: 12,
        paddingHorizontal: 15,
        fontSize: 16,
        marginBottom: 15,
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    primaryButton: {
        backgroundColor: '#FF6347',
        paddingVertical: 15,
        borderRadius: 25,
        alignItems: 'center',
        marginTop: 20,
        elevation: 3,
    },
    buttonLabel: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: 'bold',
    },
    centeredScreen: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loginHintText: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        marginBottom: 30,
    },
    promptText: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        marginBottom: 30,
    },
    fullPageLoader: {
        flex: 1,
        backgroundColor: '#FFF5E5',
    },
    marginTop12: {
        marginTop: 12,
    },
    errorText: {
        color: 'red',
        fontStyle: 'italic',
        marginBottom: 15,
    },
    disabledButton: {
        opacity: 0.5,
    },
    spacer100: {
        height: 100,
    },
    ticketCard: {
        backgroundColor: '#FFFFFF',
        padding: 30,
        borderRadius: 20,
        alignItems: 'center',
        marginHorizontal: 10,
        borderWidth: 2,
        borderColor: '#FFE394',
        borderStyle: 'dashed',
        elevation: 5,
        shadowColor: '#FF6347',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
    },
    infoText: {
        fontSize: 18,
        color: '#333333',
        marginBottom: 15,
        fontWeight: '600',
    },
    cancelBtn: {
        marginTop: 30,
        paddingVertical: 12,
        paddingHorizontal: 40,
        borderRadius: 25,
        borderWidth: 1.5,
        borderColor: '#FF6347',
        backgroundColor: '#FFF5F3',
    },
    cancelBtnText: {
        color: '#FF6347',
        fontSize: 16,
        fontWeight: 'bold',
    },
    tableGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginBottom: 15,
    },
    tableBtn: {
        width: '30%',
        backgroundColor: '#F5F5F5',
        paddingVertical: 15,
        borderRadius: 12,
        alignItems: 'center',
        marginBottom: 10,
        borderWidth: 2,
        borderColor: 'transparent',
    },
    tableBtnSelected: {
        backgroundColor: '#FFE394',
        borderColor: '#FF6347',
    },
    tableBtnDisabled: {
        backgroundColor: '#E0E0E0',
        opacity: 0.6,
    },
    tableBtnText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
    },
    tableBtnTextSelected: {
        color: '#FF6347',
    },
    tableSubText: {
        fontSize: 12,
        color: '#666',
        marginTop: 2,
    },
    tableStatusText: {
        fontSize: 10,
        color: 'red',
        fontWeight: 'bold',
        marginTop: 4,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        width: '85%',
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 25,
        elevation: 10,
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#FF6347',
        textAlign: 'center',
        marginBottom: 20,
    },
    summaryBox: {
        backgroundColor: '#FFF5E5',
        padding: 15,
        borderRadius: 12,
        marginBottom: 15,
    },
    summaryText: {
        fontSize: 16,
        color: '#333',
        marginBottom: 8,
    },
    warningText: {
        fontSize: 13,
        color: '#888',
        fontStyle: 'italic',
        textAlign: 'center',
        marginBottom: 20,
    },
    modalActionRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    modalCancelBtn: {
        flex: 1,
        paddingVertical: 12,
        alignItems: 'center',
        marginRight: 10,
        borderRadius: 12,
        backgroundColor: '#F5F5F5',
    },
    modalCancelText: {
        color: '#666',
        fontWeight: 'bold',
        fontSize: 16,
    },
    modalConfirmBtn: {
        flex: 1,
        paddingVertical: 12,
        alignItems: 'center',
        borderRadius: 12,
        backgroundColor: '#FF6347',
    },
    modalConfirmText: {
        color: '#FFF',
        fontWeight: 'bold',
        fontSize: 16,
    },
    centeredContent: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 24,
    },
    loginPromptText: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        marginBottom: 30,
    },
    loadingIndicator: {
        flex: 1,
        backgroundColor: '#FFF5E5',
    },
    primaryButtonMarginTop: {
        marginTop: 12,
    },
});