import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFF5E5',
        paddingLeft: 15,
        paddingRight: 15,
    },
    scrollContent: {
        paddingBottom: 300,
    },
    headerContainer: {
        alignItems: 'center',
        marginTop: 30,
        marginBottom: 20,
    },
    titleText: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#FF6347',
        marginTop: 15,
    },
    subText: {
        fontSize: 20,
        color: '#666',
        marginTop: 5,
        textAlign: 'center',
    },
    errorText: {
        textAlign: 'center',
        fontSize: 14,
    },
    formContainer: {
        backgroundColor: '#F69D39',
        padding: 20,
        marginHorizontal: 20,
        borderRadius: 25,
        elevation: 3,
    },
    input: {
        marginBottom: 12,
        backgroundColor: '#F69D39',
    },
    primaryButton: {
        paddingVertical: 6,
        backgroundColor: '#FFE394',
        borderRadius: 25,
        elevation: 2,
        marginTop: 10,
    },
    buttonLabel: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#FF6347',
    },
    forgotPassword: {
        textAlign: 'right',
        color: '#b9422a',
        marginTop: 5,
        marginBottom: 20,
        fontWeight: '600',
    },
    logoImage: {
        width: 120,
        height: 120,
        resizeMode: 'contain',
    },
    avatarPickerBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 15,
        borderWidth: 1.5,
        borderColor: '#FF6347',
        borderStyle: 'dashed',
        borderRadius: 12,
        marginBottom: 15,
        marginTop: 5,
        backgroundColor: '#FFF5F3',
    },
    avatarPickerText: {
        color: '#FF6347',
        fontWeight: 'bold',
        fontSize: 16,
    },
    avatarPreview: {
        width: 100,
        height: 100,
        borderRadius: 50,
        alignSelf: 'center',
        marginBottom: 20,
        borderWidth: 2,
        borderColor: '#FF6347',
    },
    profileContainer: {
        flex: 1,
        backgroundColor: '#F5F5F5',
    },
    headerBackground: {
        backgroundColor: '#FF6347',
        height: 120,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
    },
    profileInfoWrapper: {
        alignItems: 'center',
        marginTop: -60,
        marginBottom: 20,
    },
    avatarWrapper: {
        width: 110,
        height: 110,
        borderRadius: 55,
        backgroundColor: '#ffffff',
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    profileAvatar: {
        width: 100,
        height: 100,
        borderRadius: 50,
    },
    nameText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#333333',
        marginTop: 10,
    },
    usernameText: {
        fontSize: 16,
        color: '#666666',
        marginTop: 2,
    },
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        backgroundColor: '#ffffff',
        marginHorizontal: 20,
        paddingVertical: 15,
        borderRadius: 15,
        elevation: 2,
        marginBottom: 20,
    },
    statItem: {
        alignItems: 'center',
    },
    statNumber: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#FF6347',
    },
    statLabel: {
        fontSize: 14,
        color: '#888888',
        marginTop: 4,
    },
    menuContainer: {
        backgroundColor: '#ffffff',
        marginHorizontal: 20,
        borderRadius: 15,
        elevation: 2,
        overflow: 'hidden',
        marginBottom: 20,
    },
    logoutButton: {
        marginHorizontal: 20,
        marginBottom: 40,
        paddingVertical: 6,
        borderColor: '#FF6347',
        borderWidth: 1.5,
        borderRadius: 25,
        backgroundColor: '#FFF5F3',
    },
    logoutText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#FF6347',
    },
    accountWrapper: {
        flex: 1,
        backgroundColor: '#FFF5E5', 
    },
    accountContent: {
        flex: 1, 
        justifyContent: 'center', 
        paddingHorizontal: 20,
    },
    accountTitle: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#FF6347',
        textAlign: 'center',
        marginBottom: 10,
    },
    accountSubtitle: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        marginBottom: 30,
    },
    accountLoginBtn: {
        backgroundColor: '#FF6347',
        paddingVertical: 14,
        borderRadius: 25,
        marginBottom: 15,
        alignItems: 'center',
    },
    accountLoginText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    accountRegisterBtn: {
        backgroundColor: '#fff',
        paddingVertical: 14,
        borderRadius: 25,
        borderWidth: 1,
        borderColor: '#FF6347',
        alignItems: 'center',
    },
    accountRegisterText: {
        color: '#FF6347',
        fontWeight: 'bold',
        fontSize: 16,
    },
    header: {
        backgroundColor: '#FF6347',
        padding: 15,
        alignItems: 'center',
    },
    headerText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    emptyText: {
        textAlign: 'center',
        marginTop: 20,
        fontStyle: 'italic',
        color: 'gray',
    },
    orderCard: {
        marginBottom: 15,
        backgroundColor: '#fff',
        elevation: 2,
        borderRadius: 8,
        overflow: 'hidden',
    },
    orderAccordionHeader: {
        backgroundColor: '#fff',
    },
    statusBadge: {
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 4,
        backgroundColor: '#f0f0f0',
        borderRadius: 12,
        alignSelf: 'center',
        marginRight: 10,
    },
    detailsContainer: {
        padding: 15,
        backgroundColor: '#fafafa',
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
    },
    detailTitle: {
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#333',
    },
    foodRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
        paddingBottom: 8,
        borderBottomWidth: 0.5,
        borderBottomColor: '#ddd',
    },
    foodName: {
        fontSize: 15,
        fontWeight: '500',
        color: '#000',
    },
    foodMeta: {
        fontSize: 13,
        color: '#666',
        marginTop: 2,
    },
    foodTotal: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#FF6347',
    },
    dateText: {
        fontSize: 12,
        color: 'gray',
        marginTop: 10,
        fontStyle: 'italic',
        textAlign: 'right',
    },
    actions: {
        padding: 10,
        justifyContent: 'flex-end',
        backgroundColor: '#fff',
    },
    itemContainer: {
        backgroundColor: '#fff',
        borderRadius: 15,
        marginBottom: 15,
        overflow: 'hidden',
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    accordionHeader: {
        backgroundColor: '#fff',
        padding: 0,
    },
    actionRow: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        padding: 10,
        backgroundColor: '#fafafa',
        borderTopWidth: 1,
        borderTopColor: '#eee',
    },
    actionBtn: {
        marginLeft: 10,
        borderRadius: 8,
    },
    fab: {
        position: 'absolute',
        margin: 16,
        right: 0,
        bottom: 0,
        backgroundColor: '#FF6347',
    },
});